package ru.mc_positron.entity;

public interface EntityDataKeys {

    int FLAGS = 0;
    int HEALTH = 1; //int (minecart/boat)
    int VARIANT = 2; //int
    int COLOR = 3, DATA_COLOUR = 3; //byte
    int NAMETAG = 4; //string
    int OWNER_EID = 5; //long
    int TARGET_EID = 6; //long
    int AIR = 7; //short
    int POTION_COLOR = 8; //int (ARGB!)
    int POTION_AMBIENT = 9; //byte
    int JUMP_DURATION = 10; //long
    int HURT_TIME = 11; //int (minecart/boat)
    int HURT_DIRECTION = 12; //int (minecart/boat)
    int PADDLE_TIME_LEFT = 13; //float
    int PADDLE_TIME_RIGHT = 14; //float
    int EXPERIENCE_VALUE = 15; //int (xp orb)
    int DISPLAY_ITEM = 16; //int (id | (data << 16))
    int DISPLAY_OFFSET = 17; //int
    int HAS_DISPLAY = 18; //byte (must be 1 for minecart to show block inside)
    int SWELL = 19;
    int OLD_SWELL = 20;
    int SWELL_DIR = 21;
    int CHARGE_AMOUNT = 22;
    int ENDERMAN_HELD_RUNTIME_ID = 23; //short
    int ENTITY_AGE = 24; //short
    int PLAYER_FLAGS = 26; //byte
    int PLAYER_INDEX = 27;
    int PLAYER_BED_POSITION = 28; //block coords
    int FIREBALL_POWER_X = 29; //float
    int FIREBALL_POWER_Y = 30;
    int FIREBALL_POWER_Z = 31;
    int AUX_POWER = 32;
    int FISH_X = 33;
    int FISH_Z = 34;
    int FISH_ANGLE = 35;
    int POTION_AUX_VALUE = 36; //short
    int LEAD_HOLDER_EID = 37; //long
    int SCALE = 38; //float
    int HAS_NPC_COMPONENT = 39; //byte
    int NPC_SKIN_ID = 40; //string
    int URL_TAG = 41; //string
    int MAX_AIR = 42; //short
    int MARK_VARIANT = 43; //int
    int CONTAINER_TYPE = 44; //byte
    int CONTAINER_BASE_SIZE = 45; //int
    int CONTAINER_EXTRA_SLOTS_PER_STRENGTH = 46; //int
    int BLOCK_TARGET = 47; //block coords (ender crystal)
    int WITHER_INVULNERABLE_TICKS = 48; //int
    int WITHER_TARGET_1 = 49; //long
    int WITHER_TARGET_2 = 50; //long
    int WITHER_TARGET_3 = 51; //long
    int AERIAL_ATTACK = 52;
    int BOUNDING_BOX_WIDTH = 53; //float
    int BOUNDING_BOX_HEIGHT = 54; //float
    int FUSE_LENGTH = 55; //int
    int RIDER_SEAT_POSITION = 56; //vector3f
    int RIDER_ROTATION_LOCKED = 57; //byte
    int RIDER_MAX_ROTATION = 58; //float
    int RIDER_MIN_ROTATION = 59; //float
    int RIDER_ROTATION_OFFSET = 60;
    int AREA_EFFECT_CLOUD_RADIUS = 61; //float
    int AREA_EFFECT_CLOUD_WAITING = 62; //int
    int AREA_EFFECT_CLOUD_PARTICLE_ID = 63; //int
    int SHULKER_PEEK_ID = 64; //int
    int SHULKER_ATTACH_FACE = 65; //byte
    int SHULKER_ATTACHED = 66; //short
    int SHULKER_ATTACH_POS = 67; //block coords
    int TRADING_PLAYER_EID = 68; //long
    int TRADING_CAREER = 69;
    int HAS_COMMAND_BLOCK = 70;
    int COMMAND_BLOCK_COMMAND = 71; //string
    int COMMAND_BLOCK_LAST_OUTPUT = 72; //string
    int COMMAND_BLOCK_TRACK_OUTPUT = 73; //byte
    int CONTROLLING_RIDER_SEAT_NUMBER = 74; //byte
    int STRENGTH = 75; //int
    int MAX_STRENGTH = 76; //int
    int SPELL_CASTING_COLOR = 77; //int
    int LIMITED_LIFE = 78;
    int ARMOR_STAND_POSE_INDEX = 79; // int
    int ENDER_CRYSTAL_TIME_OFFSET = 80; // int
    int ALWAYS_SHOW_NAMETAG = 81; // byte
    int COLOR_2 = 82; // byte
    int NAME_AUTHOR = 83;
    int SCORE_TAG = 84; // String
    int BALLOON_ATTACHED_ENTITY = 85; // long
    int PUFFERFISH_SIZE = 86;
    int BUBBLE_TIME = 87;
    int AGENT = 88;
    int SITTING_AMOUNT = 89;
    int SITTING_AMOUNT_PREVIOUS = 90;
    int EATING_COUNTER = 91;
    int FLAGS_EXTENDED = 92;
    int LAYING_AMOUNT = 93;
    int LAYING_AMOUNT_PREVIOUS = 94;
    int DURATION = 95;
    int SPAWN_TIME = 96;
    int CHANGE_RATE = 97;
    int CHANGE_ON_PICKUP = 98;
    int PICKUP_COUNT = 99;
    int INTERACTIVE_TAG = 100; //string (button text)
    int TRADE_TIER = 101;
    int MAX_TRADE_TIER = 102;
    int TRADE_EXPERIENCE = 103;
    int SKIN_ID = 104; // int ???
    int SPAWNING_FRAMES = 105;
    int COMMAND_BLOCK_TICK_DELAY = 106;
    int COMMAND_BLOCK_EXECUTE_ON_FIRST_TICK = 107;
    int AMBIENT_SOUND_INTERVAL = 108;
    int AMBIENT_SOUND_INTERVAL_RANGE = 109;
    int AMBIENT_SOUND_EVENT_NAME = 110;
    int FALL_DAMAGE_MULTIPLIER = 111;
    int NAME_RAW_TEXT = 112;
    int CAN_RIDE_TARGET = 113;
    int LOW_TIER_CURED_DISCOUNT = 114;
    int HIGH_TIER_CURED_DISCOUNT = 115;
    int NEARBY_CURED_DISCOUNT = 116;
    int NEARBY_CURED_DISCOUNT_TIMESTAMP = 117;
    int HITBOX = 118;
    int IS_BUOYANT = 119;
    int FREEZING_EFFECT_STRENGTH = 120;
    int BUOYANCY_DATA = 121;
    int GOAT_HORN_COUNT = 122;
    int BASE_RUNTIME_ID = 123;
    int MOVEMENT_SOUND_DISTANCE_OFFSET = 124;
    int HEARTBEAT_INTERVAL_TICKS = 125;
    int HEARTBEAT_SOUND_EVENT = 126;
    int PLAYER_LAST_DEATH_POS = 127;
    int PLAYER_LAST_DEATH_DIMENSION = 128;
    int PLAYER_HAS_DIED = 129;
}
